####################################################################
#  Example SGE submit script  
#  run namd2 job with GPU using fast interface and updated openmpi
####################################################################

#$ -V
#$ -cwd
#$ -pe orte 4
#$ -q gpu   
#$ -N JobName
#$ -e JobName.err
#$ -o JobName.out
#$ -S /bin/bash
#$ -l h_vmem=20G

# Set path for openmpi 
MPIDIR=/share/apps/openmpi/gnu/eth
MPIRUN=$MPIDIR/bin/mpirun

# Set path for namd
NAMDDIR=/share/apps/namd-cuda/2.9
NAMD2=$NAMDDIR/bin/namd2

# Set path for cuda
CUDADIR=/opt/cuda

# Export Library path
export LD_LIBRARY_PATH=$MPIDIR/lib:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=$NAMDDIR/lib:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=$CUDADIR/lib64:$LD_LIBRARY_PATH

# Use fast interface for communication 
MCA="--mca btl_tcp_if_include 10.3.0.0/16 --mca btl tcp,self"

# run job in your directory with your data
cd /data/scratch/your-account/your/data/path
$MPIRUN $MCA -np $NSLOTS $NAMD2 +idelpoll prog.conf > JobName.log
